version: '2.4'

services:
  redis:
    image: redis:6.0.6-alpine
    cpus: '0.25'
    mem_limit: '128m'
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres:11.8-alpine
    cpus: "1"
    mem_limit: "1g"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  redis:
    driver: local
  postgres:
    driver: local
