default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>

development:
  <<: *default
  database: amazutech_development

test:
  <<: *default
  database: amazutech_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  pool: <%= ENV['RAILS_MAX_THREADS'] || 10 %>
  timeout: 5000
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
