default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: 0.0.0.0
  port: 5432

development:
  <<: *default
  database: amazutech_development

test:
  <<: *default
  database: amazutech_test

production:
  url:  <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DATABASE_POOL'] || 5 %>
